project_id = "jnfwmdirvnqfpfhtipld"

[functions.get-train-departures]
verify_jwt = false

[functions.claim-assistant]
verify_jwt = false
[functions.collect-raw-departures]
enabled = true
verify_jwt = true
import_map = "./functions/collect-raw-departures/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/collect-raw-departures/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/collect-raw-departures/*.html" ]
