// send-delay-push — Web Push for new claimable delays on monitored commute routes.
//
// The push analogue of send-claim-digest: per subscribed user, match
// v_claimable_journeys against commute_routes (both directions, per-direction
// time windows, monitored_days), minus already-claimed, minus already-pushed
// (push_log). UNLIKE the digest it only looks at the last ~2 days
// (origin_local_date >= today-1) — push is "just happened", never the 90-day
// backlog, so a first-time subscriber gets nothing retroactive.
//
// Deployed with verify_jwt=false (pg_cron POSTs headerless — §15 trap).
// Body {"dryRun": true} reports would-send per user without sending/logging.
//
// Secrets: VAPID_PUBLIC_KEY / VAPID_PRIVATE_KEY (base64url, as generated by
// `npx web-push generate-vapid-keys` — converted to JWK below), VAPID_SUBJECT.

import { createClient } from "jsr:@supabase/supabase-js@2";
import * as webpush from "jsr:@negrel/webpush@0.3";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const VAPID_PUBLIC_KEY = Deno.env.get("VAPID_PUBLIC_KEY") ?? "";
const VAPID_PRIVATE_KEY = Deno.env.get("VAPID_PRIVATE_KEY") ?? "";
const VAPID_SUBJECT = Deno.env.get("VAPID_SUBJECT") ?? "mailto:kontakt@qvitta.nu";
const APP_URL = "https://qvitta.nu";

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);

function b64url(bytes: Uint8Array): string {
  return btoa(String.fromCharCode(...bytes)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
function fromB64url(s: string): Uint8Array {
  const pad = "=".repeat((4 - (s.length % 4)) % 4);
  return Uint8Array.from(atob((s + pad).replace(/-/g, "+").replace(/_/g, "/")), (c) => c.charCodeAt(0));
}

/** web-push-style raw base64url VAPID keys → the JWK pair @negrel/webpush imports. */
async function importVapid(): Promise<webpush.ApplicationServer> {
  const pub = fromB64url(VAPID_PUBLIC_KEY); // 65-byte uncompressed P-256 point (0x04 x y)
  const d = VAPID_PRIVATE_KEY;
  const x = b64url(pub.slice(1, 33));
  const y = b64url(pub.slice(33, 65));
  const jwkBase = { kty: "EC", crv: "P-256", x, y };
  const vapidKeys = await webpush.importVapidKeys(
    {
      publicKey: { ...jwkBase, key_ops: [], ext: true },
      privateKey: { ...jwkBase, d, key_ops: ["sign"], ext: true },
    },
    { extractable: false }
  );
  return await webpush.ApplicationServer.new({ contactInformation: VAPID_SUBJECT, vapidKeys });
}

interface Route {
  user_id: string;
  from_stop_id: string;
  to_stop_id: string;
  outbound_start_time: string | null;
  outbound_end_time: string | null;
  return_start_time: string | null;
  return_end_time: string | null;
  monitored_days: number[];
}

interface JourneyRow {
  journey_key: string;
  origin_stop_id: string;
  destination_stop_id: string;
  origin_stop_name: string;
  destination_stop_name: string;
  origin_scheduled: string;
  origin_local_date: string;
  destination_delay_minutes: number | null;
  canceled: boolean | null;
}

const STHLM = "Europe/Stockholm";

function localHHMM(ts: string): string {
  return new Date(ts).toLocaleTimeString("sv-SE", { timeZone: STHLM, hour: "2-digit", minute: "2-digit" });
}
function isoWeekday(dateStr: string): number {
  const d = new Date(`${dateStr}T12:00:00Z`).getUTCDay(); // 0=Sun
  return d === 0 ? 7 : d;
}
function inWindow(hhmm: string, start: string | null, end: string | null): boolean {
  if (!start || !end) return true; // unset window = that direction matches all day
  const s = start.slice(0, 5);
  const e = end.slice(0, 5);
  return hhmm >= s && hhmm <= e;
}

/** Same matching semantics as the digest: outbound O→D in the outbound window, reverse in the return window, gated on monitored_days. */
function journeyMatchesRoute(j: JourneyRow, r: Route): boolean {
  if (r.monitored_days.length === 0) return false; // paused route
  if (!r.monitored_days.includes(isoWeekday(j.origin_local_date))) return false;
  const hhmm = localHHMM(j.origin_scheduled);
  if (j.origin_stop_id === r.from_stop_id && j.destination_stop_id === r.to_stop_id) {
    return inWindow(hhmm, r.outbound_start_time, r.outbound_end_time);
  }
  if (j.origin_stop_id === r.to_stop_id && j.destination_stop_id === r.from_stop_id) {
    return inWindow(hhmm, r.return_start_time, r.return_end_time);
  }
  return false;
}

Deno.serve(async (req) => {
  let dryRun = false;
  try {
    const body = await req.json();
    dryRun = Boolean(body?.dryRun);
  } catch {
    /* headerless cron POST with empty body */
  }

  if (!VAPID_PUBLIC_KEY || !VAPID_PRIVATE_KEY) {
    return new Response(JSON.stringify({ error: "VAPID keys not configured" }), { status: 500 });
  }

  // 1) Who is subscribed?
  const { data: subs, error: subsError } = await supabase.from("push_subscriptions").select("*");
  if (subsError) return new Response(JSON.stringify({ error: subsError.message }), { status: 500 });
  if (!subs?.length) return new Response(JSON.stringify({ users: 0, sent: 0 }), { status: 200 });

  const userIds = [...new Set(subs.map((s) => s.user_id as string))];

  // 2) Their routes.
  const { data: routes, error: routesError } = await supabase
    .from("commute_routes")
    .select("*")
    .in("user_id", userIds);
  if (routesError) return new Response(JSON.stringify({ error: routesError.message }), { status: 500 });
  const routesByUser = new Map<string, Route[]>();
  for (const r of (routes ?? []) as Route[]) {
    const list = routesByUser.get(r.user_id) ?? [];
    list.push(r);
    routesByUser.set(r.user_id, list);
  }

  // 3) Recent claimable journeys on any subscribed user's O-D pairs (one query).
  const pairs = new Set<string>();
  const orClauses: string[] = [];
  for (const r of (routes ?? []) as Route[]) {
    for (const [a, b] of [
      [r.from_stop_id, r.to_stop_id],
      [r.to_stop_id, r.from_stop_id],
    ]) {
      const key = `${a}→${b}`;
      if (!pairs.has(key)) {
        pairs.add(key);
        orClauses.push(`and(origin_stop_id.eq.${a},destination_stop_id.eq.${b})`);
      }
    }
  }
  if (orClauses.length === 0) return new Response(JSON.stringify({ users: 0, sent: 0 }), { status: 200 });

  const since = new Date(Date.now() - 24 * 3600 * 1000).toLocaleDateString("sv-SE", { timeZone: STHLM });
  const { data: journeys, error: journeysError } = await supabase
    .from("v_claimable_journeys")
    .select(
      "journey_key, origin_stop_id, destination_stop_id, origin_stop_name, destination_stop_name, origin_scheduled, origin_local_date, destination_delay_minutes, canceled"
    )
    .or(orClauses.join(","))
    .gte("origin_local_date", since)
    .limit(1000);
  if (journeysError) return new Response(JSON.stringify({ error: journeysError.message }), { status: 500 });
  if (!journeys?.length) return new Response(JSON.stringify({ users: userIds.length, sent: 0 }), { status: 200 });

  // 4) Per user: match, minus claimed, minus already-pushed.
  const appServer = dryRun ? null : await importVapid();
  const report: Record<string, unknown>[] = [];
  let sent = 0;

  for (const userId of userIds) {
    const userRoutes = routesByUser.get(userId) ?? [];
    if (userRoutes.length === 0) continue;

    const matched = new Map<string, JourneyRow>();
    for (const j of journeys as JourneyRow[]) {
      if (!j.journey_key || matched.has(j.journey_key)) continue;
      if (userRoutes.some((r) => journeyMatchesRoute(j, r))) matched.set(j.journey_key, j);
    }
    if (matched.size === 0) continue;

    const keys = [...matched.keys()];
    const [{ data: claimed }, { data: pushed }] = await Promise.all([
      supabase.from("claims").select("journey_key").eq("user_id", userId).in("journey_key", keys),
      supabase.from("push_log").select("journey_key").eq("user_id", userId).in("journey_key", keys),
    ]);
    for (const c of claimed ?? []) matched.delete(c.journey_key as string);
    for (const p of pushed ?? []) matched.delete(p.journey_key as string);
    if (matched.size === 0) continue;

    const list = [...matched.values()];
    const first = list[0];
    const title = list.length === 1 ? "Försenat tåg på din pendlingsrutt" : `${list.length} nya förseningar på din pendlingsrutt`;
    const detail = first.canceled
      ? `${first.origin_stop_name} → ${first.destination_stop_name} ${localHHMM(first.origin_scheduled)} ställdes in.`
      : `${first.origin_stop_name} → ${first.destination_stop_name} ${localHHMM(first.origin_scheduled)} var ${first.destination_delay_minutes ?? "?"} min sent.`;
    const body =
      (list.length === 1 ? detail : `${detail} +${list.length - 1} till.`) + " Tryck för att ansöka om ersättning.";
    const payload = JSON.stringify({ title, body, url: `${APP_URL}/my-delays`, count: list.length });

    if (dryRun) {
      report.push({ user_id: userId, would_push: list.length, keys });
      continue;
    }

    // 5) Send to every device the user registered; drop expired subscriptions.
    let delivered = false;
    for (const sub of subs.filter((s) => s.user_id === userId)) {
      try {
        const subscriber = appServer!.subscribe({
          endpoint: sub.endpoint as string,
          keys: { p256dh: sub.p256dh as string, auth: sub.auth as string },
        });
        await subscriber.pushTextMessage(payload, { urgency: webpush.Urgency.High });
        delivered = true;
      } catch (err) {
        const status = (err as { response?: { status?: number } })?.response?.status;
        if (status === 404 || status === 410) {
          await supabase.from("push_subscriptions").delete().eq("endpoint", sub.endpoint as string);
        } else {
          console.error(`push failed for user ${userId}:`, err);
        }
      }
    }

    // Log once per journey per user, only if at least one device got it —
    // a fully-failed send stays eligible for the next run.
    if (delivered) {
      sent++;
      const { error: logError } = await supabase
        .from("push_log")
        .upsert(keys.map((k) => ({ user_id: userId, journey_key: k })), {
          onConflict: "user_id,journey_key",
          ignoreDuplicates: true,
        });
      if (logError) console.error("push_log insert failed:", logError.message);
      report.push({ user_id: userId, pushed: list.length });
    }
  }

  return new Response(JSON.stringify({ users: userIds.length, sent, dryRun, report }), {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });
});
