/**
 * Typed accessor over src/content/operatorStats.json — the committed data
 * snapshot behind the /forseningar/tag/<operator> pages. The JSON is
 * regenerated by scripts/refresh_station_stats.py (reads
 * dbt_dev.agg_operator_delays_daily, which accumulates daily per-label TRAIN
 * delay counts past the raw prune) at RAW-label day grain; this module owns
 * the brand merge and page selection.
 *
 * Grain note: unlike the station pages (departure events), operator stats
 * count TRAINS — a train is "late" if it was >= the threshold at ANY measured
 * stop, and it's attributed to its majority feed label. The feed's labelling
 * is noisy at contract seams (an Öresundståg through Skåne is often stamped
 * "Skånetrafiken"), so these are descriptive numbers, never a claim rule.
 *
 * Dependency-free (imported by vite.config.ts at build time for prerender).
 */
import raw from "./operatorStats.json";
import { GUIDES } from "./ersattningGuides";

type RawRow = {
  label: string;
  d: string; // ISO service date
  tr: number; // trains
  ms: number; // trains with any realtime signal
  l5: number; // trains >= 5 min late at some stop
  l20: number; // trains >= 20 min late (claim floor)
  canc: number; // cancelled trains
  sd: number; // sum of per-train max positive delay (measured trains), seconds
  mx: number; // largest delay, seconds
};

/** One day in the "Senaste dagarna" table (compact keys — ships in the JS bundle). */
export type OperatorDayStat = {
  d: string;
  /** Trains that day. */
  tr: number;
  /** Trains >= 20 min late. */
  l20: number;
  /** Cancelled trains. */
  canc: number;
  /** Largest delay that day, seconds. */
  mx: number;
};

export type OperatorStat = {
  /** Same slug as the operator's /ersattning guide — one slug per brand across the cluster. */
  slug: string;
  /** Display name, taken from the guide so the cluster never disagrees on branding. */
  name: string;
  from_date: string;
  to_date: string;
  n_trains: number;
  n_measured: number;
  n_late_5: number;
  n_late_20: number;
  n_cancelled: number;
  /** Average per-train max delay across measured trains, seconds. */
  avg_delay_seconds: number;
  max_delay_seconds: number;
  /** Latest-first per-day rows. */
  days: OperatorDayStat[];
};

/**
 * Raw feed label → guide slug. The feed carries THREE spellings of an
 * operator: information_owner (the rider brand, e.g. "Öresundståg"), the terse
 * train_owner CODE used when information_owner is null (e.g. "Ö-TÅG" — most SJ
 * trains are attributed this way), and the REST-side corporate label on Danish
 * legs ("VR Sverige AB" = Öresundståg's contractor). Verified against live
 * int_stop_events labels 2026-07-14. Labels NOT listed here get no page:
 * heritage/museum rail (Järnvägsmuseet, TJF, SKÅJ, NJ, DVVJ, BTE), brands
 * without an /ersattning guide (MTRX/VR Snabbtåg, X-Trafik, Tågab), and the
 * ambiguous bare "VR"/"RV" codes.
 */
const LABEL_TO_SLUG: Record<string, string> = {
  SJ: "sj",
  "SJ AB": "sj",
  "Skånetrafiken": "skanetrafiken",
  SKANE: "skanetrafiken",
  SL: "sl",
  SLL: "sl",
  "Västtrafik": "vasttrafik",
  VASTTRAF: "vasttrafik",
  "Öresundståg": "oresundstag",
  "Ö-TÅG": "oresundstag",
  "VR Sverige AB": "oresundstag",
  "Mälardalstrafik AB": "malartag",
  "MÄLAB": "malartag",
  "A-train": "arlandaexpress",
  ATRAIN: "arlandaexpress",
  "Jönköpings Länstrafik": "jlt",
  JLT: "jlt",
  "ÖstgötaTrafiken": "ostgotatrafiken",
  "Tåg i Bergslagen": "tagibergslagen",
  TIB: "tagibergslagen",
  "Länstrafiken Kronoberg": "kronoberg",
  "Värmlandstrafik": "varmlandstrafik",
  "Kalmar Länstrafik": "kalmar",
  Blekingetrafiken: "blekingetrafiken",
  Hallandstrafiken: "hallandstrafiken",
  "Snälltåget": "snalltaget",
  "SNÄLL": "snalltaget",
  VY: "vy",
  Vy: "vy",
  "Vy Tåg": "vy",
};

/** Below this many measured trains in the window the page is too thin to publish. */
const MIN_MEASURED_TRAINS = 50;
const DAY_ROWS = 7;

const GUIDE_NAME = new Map(GUIDES.map((g) => [g.slug, g.operator]));

export const OPERATOR_STATS_GENERATED: string = (raw as { generated: string }).generated;

function build(): OperatorStat[] {
  const rows = (raw as { rows: RawRow[] }).rows;

  // slug -> date -> summed day (merges e.g. Ö-TÅG + Öresundståg + VR Sverige AB)
  const bySlug = new Map<string, Map<string, RawRow>>();
  for (const r of rows) {
    const slug = LABEL_TO_SLUG[r.label];
    if (!slug) continue;
    const days = bySlug.get(slug) ?? bySlug.set(slug, new Map()).get(slug)!;
    const acc = days.get(r.d);
    if (!acc) {
      days.set(r.d, { ...r });
    } else {
      acc.tr += r.tr;
      acc.ms += r.ms;
      acc.l5 += r.l5;
      acc.l20 += r.l20;
      acc.canc += r.canc;
      acc.sd += r.sd;
      acc.mx = Math.max(acc.mx, r.mx);
    }
  }

  const out: OperatorStat[] = [];
  for (const [slug, dayMap] of bySlug) {
    const days = [...dayMap.values()].sort((a, b) => a.d.localeCompare(b.d));
    const n_measured = days.reduce((n, d) => n + d.ms, 0);
    if (n_measured < MIN_MEASURED_TRAINS) continue;
    const sumDelay = days.reduce((n, d) => n + d.sd, 0);
    out.push({
      slug,
      name: GUIDE_NAME.get(slug) ?? slug,
      from_date: days[0].d,
      to_date: days[days.length - 1].d,
      n_trains: days.reduce((n, d) => n + d.tr, 0),
      n_measured,
      n_late_5: days.reduce((n, d) => n + d.l5, 0),
      n_late_20: days.reduce((n, d) => n + d.l20, 0),
      n_cancelled: days.reduce((n, d) => n + d.canc, 0),
      avg_delay_seconds: n_measured ? Math.round(sumDelay / n_measured) : 0,
      max_delay_seconds: days.reduce((n, d) => Math.max(n, d.mx), 0),
      days: days
        .slice(-DAY_ROWS)
        .reverse()
        .map((d) => ({ d: d.d, tr: d.tr, l20: d.l20, canc: d.canc, mx: d.mx })),
    });
  }
  out.sort((a, b) => a.name.localeCompare(b.name, "sv"));
  return out;
}

export const OPERATORS: OperatorStat[] = build();

/** Worst-first ranking (share of trains >= 20 min late, then count). */
export const OPERATORS_WORST_FIRST: OperatorStat[] = [...OPERATORS].sort(
  (a, b) =>
    b.n_late_20 / Math.max(b.n_measured, 1) - a.n_late_20 / Math.max(a.n_measured, 1) ||
    b.n_late_20 - a.n_late_20
);

const BY_SLUG = new Map(OPERATORS.map((o) => [o.slug, o]));
export const operatorBySlug = (slug: string): OperatorStat | undefined => BY_SLUG.get(slug);

export const operatorPath = (o: OperatorStat) => `/forseningar/tag/${o.slug}`;
export const operatorUrl = (o: OperatorStat) => `https://qvitta.nu/forseningar/tag/${o.slug}`;
