/**
 * Typed accessor over src/content/stationStats.json — the committed data
 * snapshot behind the /forseningar station pages. The JSON is regenerated by
 * scripts/refresh_station_stats.py (reads dbt_dev.agg_station_delays_daily,
 * which accumulates daily per-station delay counts past the raw prune).
 *
 * Dependency-free (imported by vite.config.ts at build time for prerender).
 */
import raw from "./stationStats.json";

/** One day in the "Senaste dagarna" table (compact keys — ships in the JS bundle). */
export type StationDayStat = {
  /** ISO service date. */
  d: string;
  /** Departures that day. */
  dep: number;
  /** Departures >= 20 min late. */
  l20: number;
  /** Cancelled departures. */
  canc: number;
  /** Largest delay that day, seconds. */
  mx: number;
};

export type StationStat = {
  slug: string;
  station_id: string;
  station_name: string;
  from_date: string;
  to_date: string;
  n_departures: number;
  n_measured: number;
  n_late_5: number;
  n_late_20: number;
  n_cancelled: number;
  avg_delay_seconds: number;
  max_delay_seconds: number;
  operator_label: string | null;
  /** Latest-first per-day rows. Absent until the first refresh after 2026-07-12. */
  days?: StationDayStat[];
};

export const STATION_STATS_GENERATED: string = (raw as { generated: string }).generated;

export const STATIONS: StationStat[] = (raw as { stations: StationStat[] }).stations;

/** Worst-first ranking used by the index page and the "mest försenade" lists. */
export const STATIONS_WORST_FIRST: StationStat[] = [...STATIONS].sort(
  (a, b) => b.n_late_20 - a.n_late_20 || b.n_late_5 - a.n_late_5
);

const BY_SLUG = new Map(STATIONS.map((s) => [s.slug, s]));
export const stationBySlug = (slug: string): StationStat | undefined => BY_SLUG.get(slug);

export const stationPath = (s: StationStat) => `/forseningar/${s.slug}`;
export const stationUrl = (s: StationStat) => `https://qvitta.nu/forseningar/${s.slug}`;

/** Board deep-link: `/` with this station prefilled in the search box. */
export const stationLiveHref = (s: StationStat) =>
  `/?station=${encodeURIComponent(s.station_name)}#board`;

/* ------------------------------------------------------------------ */
/* Display helpers                                                     */
/* ------------------------------------------------------------------ */

/* Structural param types so the same helpers serve StationStat AND the
   operator stats (src/content/operatorStats.ts) — same math, same fields. */

/** Share (%) of measured departures less than 5 min late — "i tid". */
export const pctOnTime = (s: { n_measured: number; n_late_5: number }): number =>
  s.n_measured > 0 ? Math.round(((s.n_measured - s.n_late_5) / s.n_measured) * 100) : 0;

export const pctLate5 = (s: { n_measured: number; n_late_5: number }): number =>
  s.n_measured > 0 ? Math.round((s.n_late_5 / s.n_measured) * 100) : 0;

/** One decimal, Swedish comma. */
export const pctLate20 = (s: { n_measured: number; n_late_20: number }): string =>
  s.n_measured > 0 ? ((s.n_late_20 / s.n_measured) * 100).toFixed(1).replace(".", ",") : "0";

export const minutes = (seconds: number): string =>
  (seconds / 60).toFixed(1).replace(".", ",");

const WEEKDAYS = ["sön", "mån", "tis", "ons", "tors", "fre", "lör"];
const MONTHS_SHORT = ["jan", "feb", "mars", "april", "maj", "juni", "juli", "aug", "sep", "okt", "nov", "dec"];

/** Swedish short day label for a per-day row: "fre 11 juli". */
export function dayLabel(iso: string): string {
  const d = new Date(`${iso}T00:00:00`);
  if (isNaN(d.getTime())) return iso;
  return `${WEEKDAYS[d.getDay()]} ${d.getDate()} ${MONTHS_SHORT[d.getMonth()]}`;
}

/** Swedish date range "3–7 juli 2026" (falls back to ISO on odd input). */
export function periodLabel(s: { from_date: string; to_date: string }): string {
  const MONTHS = ["januari", "februari", "mars", "april", "maj", "juni", "juli", "augusti", "september", "oktober", "november", "december"];
  const f = new Date(`${s.from_date}T00:00:00`);
  const t = new Date(`${s.to_date}T00:00:00`);
  if (isNaN(f.getTime()) || isNaN(t.getTime())) return `${s.from_date} – ${s.to_date}`;
  if (f.getMonth() === t.getMonth() && f.getFullYear() === t.getFullYear()) {
    return `${f.getDate()}–${t.getDate()} ${MONTHS[t.getMonth()]} ${t.getFullYear()}`;
  }
  return `${f.getDate()} ${MONTHS[f.getMonth()]} – ${t.getDate()} ${MONTHS[t.getMonth()]} ${t.getFullYear()}`;
}

/** TV's operator label is sometimes the terse owner CODE — map to the rider brand. */
const OPERATOR_DISPLAY: Record<string, string> = {
  "Ö-TÅG": "Öresundståg",
  SKANE: "Skånetrafiken",
  MÄLAB: "Mälartåg",
  "Mälardalstrafik AB": "Mälartåg",
  VASTTRAF: "Västtrafik",
  SNÄLL: "Snälltåget",
  ATRAIN: "Arlanda Express",
  "A-train": "Arlanda Express",
  TIB: "Tåg i Bergslagen",
  VY: "Vy Tåg",
  TÅGAB: "Tågab",
  JLT: "Krösatågen (JLT)",
};

export const operatorDisplay = (label: string | null): string | null =>
  label ? OPERATOR_DISPLAY[label] ?? label : null;

/** Which /ersattning guide covers this operator brand (if any). */
const OPERATOR_GUIDE_SLUG: Record<string, string> = {
  "Öresundståg": "oresundstag",
  "Skånetrafiken": "skanetrafiken",
  "Mälartåg": "malartag",
  "Västtrafik": "vasttrafik",
  "Snälltåget": "snalltaget",
  SJ: "sj",
  SL: "sl",
  "Vy Tåg": "vy",
  "Tåg i Bergslagen": "tagibergslagen",
  "Arlanda Express": "arlandaexpress",
  "Krösatågen (JLT)": "jlt",
};

export const operatorGuideSlug = (s: StationStat): string | null => {
  const brand = operatorDisplay(s.operator_label);
  return brand ? OPERATOR_GUIDE_SLUG[brand] ?? null : null;
};
