select 
id
,scheduled
,realtime 
,arrival_delay
,canceled
,is_realtime
,route__name
,route__designation
,route__transport_mode_code
,route__transport_mode
,route__direction
,route__origin__id
,route__origin__name
,route__destination__id
,route__destination__name
,trip__trip_id
,trip__start_date
,trip__technical_number
,agency__id
,agency__name
,agency__operator
,stop__id
,stop__name
,stop__lat
,stop__lon
,scheduled_platform__id
,scheduled_platform__designation
,realtime_platform__id
,realtime_platform__designation
,alerts
,ingested_at 

from {{ source('raw', 'raw_departures') }}