CREATE TABLE public.raw_departures (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    scheduled timestamptz NOT NULL,
    realtime timestamptz,
    arrival_delay integer,
    canceled boolean,
    is_realtime boolean,
    route__name text,
    route__designation text,
    route__transport_mode_code integer,
    route__transport_mode text,
    route__direction text,
    route__origin__id text,
    route__origin__name text,
    route__destination__id text,
    route__destination__name text,
    trip__trip_id text NOT NULL,
    trip__start_date text NOT NULL,
    trip__technical_number integer,
    agency__id text,
    agency__name text,
    agency__operator text,
    stop__id text NOT NULL,
    stop__name text,
    stop__lat numeric,
    stop__lon numeric,
    scheduled_platform__id text,
    scheduled_platform__designation text,
    realtime_platform__id text,
    realtime_platform__designation text,
    alerts jsonb,
    ingested_at timestamptz DEFAULT now() NOT NULL,
    UNIQUE (trip__trip_id, trip__start_date, stop__id, scheduled, ingested_at)
);